### ISSUE TITLE
Compilation Error: Deprecated Registrar Class in razorpay_flutter Plugin v1.3.7  Feel free to modify it if you think of anything more fitting!

### ISSUE THREAD

**Issue by iamraghavan** [razorpay/razorpay-flutter#434]
# Bug Report 

![Image](https://github.com/user-attachments/assets/10395224-d8c9-4f78-9f97-8041f67068a6)

![Image](https://github.com/user-attachments/assets/58261d14-4fec-4517-8ec2-7224b250dc96)

Compilation Error in Razorpay Flutter Plugin

## Description

The errors you're encountering with the Razorpay Flutter plugin are primarily due to the use of an outdated version of the plugin that relies on the old Flutter plugin embedding API. The `Registrar` class is part of that old API, which has been deprecated and removed in newer versions of Flutter.

### Plugin Version
- `razorpay_flutter` version: 1.3.7

## Error Messages

```
warning: [options] source value 8 is obsolete and will be removed in a future release warning: [options] target value 8 is obsolete and will be removed in a future release warning: [options] To suppress warnings about obsolete options, use -Xlint:-options. C:\Users\Raghavan PC\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.7\android\src\main\java\com\razorpay\razorpay_flutter\RazorpayFlutterPlugin.java:18: error: cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar; ^ symbol: class Registrar location: interface PluginRegistry C:\Users\Raghavan PC\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.7\android\src\main\java\com\razorpay\razorpay_flutter\RazorpayFlutterPlugin.java:36: error: cannot find symbol public static void registerWith(Registrar registrar) { ^ symbol: class Registrar location: class RazorpayFlutterPlugin C:\Users\Raghavan PC\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.7\android\src\main\java\com\razorpay\razorpay_flutter\RazorpayFlutterPlugin.java:56: error: cannot find symbol private RazorpayFlutterPlugin(Registrar registrar) { ^ symbol: class Registrar location: class RazorpayFlutterPlugin Note: C:\Users\Raghavan PC\AppData\Local\Pub\Cache\hosted\pub.dev\razorpay_flutter-1.3.7\android\src\main\java\com\razorpay\razorpay_flutter\RazorpayDelegate.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. 3 errors 3 warnings

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':razorpay_flutter:compileReleaseJavaWithJavac'. > Compilation failed; see the compiler error output for details.

Try: > Run with --info option to get more log output. > Run with --scan to get full insights.

BUILD FAILED in 43s Running Gradle task 'assembleRelease'... 44.2s Gradle task assembleRelease failed with exit code 1
```

## Steps to Reproduce

1. Use `razorpay_flutter` version 1.3.7.
2. Attempt to build the project.
3. Observe the compilation errors related to the `Registrar` class.

## Expected Behavior

The project should compile without errors.

## Actual Behavior

The compilation fails with errors indicating that the `Registrar` class cannot be found.

## Potential Solutions

- Upgrade to the latest version of the `razorpay_flutter` plugin which supports the new Flutter plugin embedding API.
- Modify the plugin code to remove the dependency on the `Registrar` class and use the new API.

## Environment

- Flutter version: (please specify)
- Dart version: (please specify)
- Operating system: (please specify)

## Additional Context

The use of deprecated APIs can lead to compatibility issues with newer versions of Flutter. It is recommended to keep all dependencies up-to-date to avoid such issues.

---

**Comment by Sjsan69** [comment]
fixed the issue in #435 you can view and add it to yours

**Comment by jeetchheda** [comment]
Somebody please get this issue tested and live🥲. I just did a fresh upgrade of my flutter sdk and packages. It would be unfair to downgrade just to be able to use this package.😥

**Comment by Sjsan69** [comment]
You can just use my forked repo and point it toward my repo for the package it's working fine in my project for payments via razorpay

**Comment by jeetchheda** [comment]
> Razorpay has upgraded the Flutter SDK and released the official SDK version on [pub.dev](pub.dev) This would be beneficial.

I am still not able to see any version above 1.3.7 which is still published 8 months ago. And i tried with this version, The patch isn't there.

**Comment by kapil708** [comment]
This solution works for me. [LINK](https://github.com/razorpay/razorpay-flutter/issues/432#issuecomment-2671251143)

**Comment by Sahad2701** [comment]
```yaml
dependencies:
  razorpay_flutter:
    git:
      url: https://github.com/razorpay/razorpay-flutter.git
      ref: 4cd605b291a495bf43a14d1fbdf751811545c822
```

**Note:**
This is a temporary fix until the PR is merged and a new version is released.
